name: book_library
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  http: ^1.2.0
  riverpod: ^2.5.0
  flutter_riverpod: ^2.4.10
  audioplayers: ^5.2.1
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  image_picker: ^1.0.7
  cloud_firestore: ^4.15.9
  uuid: ^4.3.3
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  carousel_slider: ^4.2.1
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  share_plus: ^9.0.0
  go_router: ^14.0.2
  gif: ^2.3.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
